# Uncomment the next line to define a global platform for your project
 platform :ios, '11.0'

target 'erg' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for erg
	
    pod 'Firebase/Core'
    pod 'Firebase/Database'
    pod 'Firebase/Auth'
    pod 'GoogleMobileVision/TextDetector'
    pod 'YXWaveView'
#    pod 'SwiftOCR'

# Linting tool
    pod 'SwiftLint'
    
  target 'ergTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
